#!/usr/bin/env bash

export APP_PORT=${APP_PORT:-80}
export DB_PORT=${DB_PORT:-3306}
export DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-secret}
export DB_DATABASE=${DB_DATABASE:-homestead}
export DB_USER=${DB_USER:-homestead}
export DB_PASSWORD=${DB_PASSWORD:-secret}
export DB_TZ=${DB_TZ:-'America/Montreal'}

COMPOSE_FILE="dev"

# Disable pseudo-TTY allocation for CI (Jenkins)
TTY=""

if [ ! -z "$BUILD_NUMBER" ]; then
    COMPOSE_FILE="ci"
    TTY="-T"
fi

COMPOSE="docker-compose -f docker-compose.$COMPOSE_FILE.yml"

if [ $# -gt 0 ]; then
    if [ "$1" == "art" ]; then
        shift 1
        $COMPOSE run --rm $TTY \
            -w /var/www/html \
            app \
            php artisan "$@"
    elif [ "$1" == "composer" ]; then
        shift 1
        $COMPOSE run --rm $TTY \
        -w /var/www/html \
        app \
        composer "$@"
    elif [ "$1" == "test" ]; then
        shift 1
        $COMPOSE run --rm $TTY \
        -w /var/www/html \
        app \
        ./vendor/bin/phpunit "$@"
    elif [ "$1" == "t" ]; then
        shift 1
        $COMPOSE exec \
        app \
        sh -c "cd /var/www/html && ./vendor/bin/phpunit $@"
    elif [ "$1" == "npm" ]; then
        shift 1
        $COMPOSE run --rm $TTY \
        -w /var/www/html \
        node \
        npm "$@"
    else
        $COMPOSE "$@"
    fi
else
    $COMPOSE ps
fi